version: 2.1

orbs:
  virtuaexecutors: virtuaorbs/executors@0.1.0
  virtuacommands: virtuaorbs/commands@0.3.0

jobs:
  tests-job:
    docker:
      - image: circleci/ruby:3.0.3
      - image: mongo:5.0.12
    steps:
      - virtuacommands/run-test-suites
  docker-job:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Authenticate on Docker HUB from environment variable
          command: echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
      - run:
          name: Set the version to be used in later steps
          command: export DATETIME=`date +%Y-%m-%d_%H.%M.%S` && echo "export VERSION=${DATETIME}" >> $BASH_ENV
      - run:
          name: Build the docker image from the Dockerfile
          command: docker build -t ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:${VERSION} -f deployment/Dockerfile .
      - run:
          name: Push the image to Docker HUB
          command: docker push ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:${VERSION}
  deployment-approval:
    type: approval
    requires:
      - docker-job
  deployment-job:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: Add trace to ensure that validation is ok and to display latest tag for Docker
          command: docker images | awk '{print $1}' | awk 'NR==2'


workflows:
  version: 2.1
  build:
    jobs:
      - tests-job
      - docker-job:
          requires:
            - tests-job
      - deployment-approval:
          requires:
            - docker-job
      - deployment-job:
          requires:
            - deployment-approval