version: 2.1

executors:
  mongoruby:
    docker:
      - image: cimg/ruby:3.1.3
      - image: mongo:5.0.12

orbs:
  virtuaexecutors: virtuaorbs/executors@0.1.0
  virtuacommands: virtuaorbs/commands@0.5.1

jobs:
  test-job:
    executor: mongoruby
    parallelism: 5
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: gem install bundler && bundle install
      - run:
          name: Test files storage
          command: |
            echo $(circleci tests glob “spec/**/*_spec.rb” | circleci tests split --split-by=filesize)
            export TESTFILES=$(circleci tests glob “spec/**/*_spec.rb” | circleci tests split --split-by=filesize) && echo "export TESTS=${TESTFILES}" >> $BASH_ENV
      - run:
          name: Test files traces
          command: echo ${TESTS}
      # - run:
      #     name: Run tests
      #     command: bundle exec rspec --format RspecJunitFormatter -o test/reports/rspec.xml ${TESTS}
      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: test/reports/rspec.xml
          destination: rspec.xml
  lint-job:
    docker:
      - image: cimg/ruby:3.1.3
    steps:
      - virtuacommands/perform-rubocop-analysis:
          directories: controllers/
  docker-job:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Authenticate on Docker HUB from environment variable
          command: echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
      - run:
          name: Set the version to be used in later steps
          command: export DATETIME=`date +%Y-%m-%d_%H.%M.%S` && echo "export VERSION=${DATETIME}" >> $BASH_ENV
      - run:
          name: Build the docker image from the Dockerfile
          command: docker build -t ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:${VERSION} -f deployment/Dockerfile .
      - run:
          name: Push the image to Docker HUB
          command: docker push ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:${VERSION}

workflows:
  version: 2.1
  build:
    jobs:
      - test-job
      - lint-job
      - docker-job:
          requires:
            - test-job
            - lint-job