version: 2.1

executors:
  mongoruby:
    docker:
      - image: cimg/ruby:3.1.3
      - image: mongo:5.0.12

orbs:
  virtuaexecutors: virtuaorbs/executors@0.1.0
  virtuacommands: virtuaorbs/commands@0.5.1

jobs:
  test-job:
    parameters:
      folders:
        type: string
        default: ""
    executor: mongoruby
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: gem install bundler && bundle install
      - run:
          name: Run tests
          command: bundle exec rspec --format RspecJunitFormatter -o test/reports/rspec.xml << parameters.folders >>
      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: test/reports/rspec.xml
          destination: rspec.xml
  lint-job:
    docker:
      - image: cimg/ruby:3.1.3
    steps:
      - virtuacommands/perform-rubocop-analysis:
          directories: controllers/ models/ constants/
workflows:
  version: 2.1
  build:
    jobs:
      - test-job:
          name: tools-tests
          folders: spec/controllers/tools
      - test-job:
          name: synthesizers-tests
          folders: "spec/controllers/synthesizers spec/controllers/modules spec/controllers/links"
      - test-job:
          name: authorizations-tests
          folders: "spec/controllers/accounts spec/controllers/applications spec/controllers/groups spec/controllers/rights spec/controllers/sessions"
      - test-job:
          name: rest-of-tests
          folders: "spec/controllers/categories spec/controllers/generators spec/controllers/memberships"
      - lint-job