version: 2.1

orbs:
  virtuaexecutors: virtuaorbs/executors@0.1.0
  virtuacommands: virtuaorbs/commands@0.3.0

jobs:
  tests-job:
    docker:
      - image: circleci/ruby:3.0.0-node-browsers
      - image: mongo:4.1.4-xenial
    steps:
      - virtuacommands/run-test-suites
  docker-job:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - echo 'export VERSION="$(date +%Y-%m-%d_%H:%M:%S)"' >> "$BASH_ENV"
      - export 
      - docker build -t ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:${VERSION} -f deployment/Dockerfile
      - docker push ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:${VERSION}

workflows:
  version: 2.1
  build:
    jobs:
      - tests-job
      - docker-job