development:
  clients:
    default:
      database: synple
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
test:
  clients:
    default:
      database: synple-test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
    iut:
      uri: <%= (ENV['MONGODB_URL'] || '').gsub('/synple', '/iut') %>
  options:
    raise_not_found_error: false