development:
  clients:
    default:
      database: virtuatable
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: virtuatable
      hosts:
        - localhost:27017